/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLiveClassesRouteImport } from './routes/admin/live-classes'
import { Route as AdminInstructorsRouteImport } from './routes/admin/instructors'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminBatchesRouteImport } from './routes/admin/batches'
import { Route as StudentSettingsRouteImport } from './routes/_student/settings'
import { Route as StudentProfileRouteImport } from './routes/_student/profile'
import { Route as StudentMyBatchesRouteImport } from './routes/_student/my-batches'
import { Route as StudentLiveClassesRouteImport } from './routes/_student/live-classes'
import { Route as StudentDashboardRouteImport } from './routes/_student/dashboard'
import { Route as StudentChallengesRouteImport } from './routes/_student/challenges'
import { Route as StudentCertificatesRouteImport } from './routes/_student/certificates'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminCoursesSlugRouteImport } from './routes/admin/courses/$slug'
import { Route as StudentPlaygroundSlugRouteImport } from './routes/_student/playground.$slug'
import { Route as StudentMeetingsSessionIdRouteImport } from './routes/_student/meetings.$sessionId'
import { Route as StudentLearnSlugRouteImport } from './routes/_student/learn.$slug'

const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveClassesRoute = AdminLiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorsRoute = AdminInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AdminRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMyBatchesRoute = StudentMyBatchesRouteImport.update({
  id: '/my-batches',
  path: '/my-batches',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLiveClassesRoute = StudentLiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentChallengesRoute = StudentChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminCoursesSlugRoute = AdminCoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const StudentPlaygroundSlugRoute = StudentPlaygroundSlugRouteImport.update({
  id: '/playground/$slug',
  path: '/playground/$slug',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMeetingsSessionIdRoute =
  StudentMeetingsSessionIdRouteImport.update({
    id: '/meetings/$sessionId',
    path: '/meetings/$sessionId',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentLearnSlugRoute = StudentLearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/roadmaps': typeof RoadmapsRoute
  '/certificates': typeof StudentCertificatesRoute
  '/challenges': typeof StudentChallengesRoute
  '/dashboard': typeof StudentDashboardRoute
  '/live-classes': typeof StudentLiveClassesRoute
  '/my-batches': typeof StudentMyBatchesRoute
  '/profile': typeof StudentProfileRoute
  '/settings': typeof StudentSettingsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/live-classes': typeof AdminLiveClassesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/students': typeof AdminStudentsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/learn/$slug': typeof StudentLearnSlugRoute
  '/meetings/$sessionId': typeof StudentMeetingsSessionIdRoute
  '/playground/$slug': typeof StudentPlaygroundSlugRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/roadmaps': typeof RoadmapsRoute
  '/certificates': typeof StudentCertificatesRoute
  '/challenges': typeof StudentChallengesRoute
  '/dashboard': typeof StudentDashboardRoute
  '/live-classes': typeof StudentLiveClassesRoute
  '/my-batches': typeof StudentMyBatchesRoute
  '/profile': typeof StudentProfileRoute
  '/settings': typeof StudentSettingsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/live-classes': typeof AdminLiveClassesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/students': typeof AdminStudentsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/learn/$slug': typeof StudentLearnSlugRoute
  '/meetings/$sessionId': typeof StudentMeetingsSessionIdRoute
  '/playground/$slug': typeof StudentPlaygroundSlugRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_student': typeof StudentRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/roadmaps': typeof RoadmapsRoute
  '/_student/certificates': typeof StudentCertificatesRoute
  '/_student/challenges': typeof StudentChallengesRoute
  '/_student/dashboard': typeof StudentDashboardRoute
  '/_student/live-classes': typeof StudentLiveClassesRoute
  '/_student/my-batches': typeof StudentMyBatchesRoute
  '/_student/profile': typeof StudentProfileRoute
  '/_student/settings': typeof StudentSettingsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/live-classes': typeof AdminLiveClassesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/students': typeof AdminStudentsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/_student/learn/$slug': typeof StudentLearnSlugRoute
  '/_student/meetings/$sessionId': typeof StudentMeetingsSessionIdRoute
  '/_student/playground/$slug': typeof StudentPlaygroundSlugRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community'
    | '/events'
    | '/login'
    | '/mentorship'
    | '/practice'
    | '/register'
    | '/roadmaps'
    | '/certificates'
    | '/challenges'
    | '/dashboard'
    | '/live-classes'
    | '/my-batches'
    | '/profile'
    | '/settings'
    | '/admin/batches'
    | '/admin/courses'
    | '/admin/instructors'
    | '/admin/live-classes'
    | '/admin/login'
    | '/admin/students'
    | '/courses/$slug'
    | '/admin/'
    | '/courses/'
    | '/learn/$slug'
    | '/meetings/$sessionId'
    | '/playground/$slug'
    | '/admin/courses/$slug'
    | '/admin/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/events'
    | '/login'
    | '/mentorship'
    | '/practice'
    | '/register'
    | '/roadmaps'
    | '/certificates'
    | '/challenges'
    | '/dashboard'
    | '/live-classes'
    | '/my-batches'
    | '/profile'
    | '/settings'
    | '/admin/batches'
    | '/admin/instructors'
    | '/admin/live-classes'
    | '/admin/login'
    | '/admin/students'
    | '/courses/$slug'
    | '/admin'
    | '/courses'
    | '/learn/$slug'
    | '/meetings/$sessionId'
    | '/playground/$slug'
    | '/admin/courses/$slug'
    | '/admin/courses'
  id:
    | '__root__'
    | '/'
    | '/_student'
    | '/admin'
    | '/community'
    | '/events'
    | '/login'
    | '/mentorship'
    | '/practice'
    | '/register'
    | '/roadmaps'
    | '/_student/certificates'
    | '/_student/challenges'
    | '/_student/dashboard'
    | '/_student/live-classes'
    | '/_student/my-batches'
    | '/_student/profile'
    | '/_student/settings'
    | '/admin/batches'
    | '/admin/courses'
    | '/admin/instructors'
    | '/admin/live-classes'
    | '/admin/login'
    | '/admin/students'
    | '/courses/$slug'
    | '/admin/'
    | '/courses/'
    | '/_student/learn/$slug'
    | '/_student/meetings/$sessionId'
    | '/_student/playground/$slug'
    | '/admin/courses/$slug'
    | '/admin/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRoute: typeof StudentRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MentorshipRoute: typeof MentorshipRoute
  PracticeRoute: typeof PracticeRoute
  RegisterRoute: typeof RegisterRoute
  RoadmapsRoute: typeof RoadmapsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-classes': {
      id: '/admin/live-classes'
      path: '/live-classes'
      fullPath: '/admin/live-classes'
      preLoaderRoute: typeof AdminLiveClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructors': {
      id: '/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/settings': {
      id: '/_student/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/profile': {
      id: '/_student/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/my-batches': {
      id: '/_student/my-batches'
      path: '/my-batches'
      fullPath: '/my-batches'
      preLoaderRoute: typeof StudentMyBatchesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/live-classes': {
      id: '/_student/live-classes'
      path: '/live-classes'
      fullPath: '/live-classes'
      preLoaderRoute: typeof StudentLiveClassesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/dashboard': {
      id: '/_student/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/challenges': {
      id: '/_student/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof StudentChallengesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/certificates': {
      id: '/_student/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/courses/$slug': {
      id: '/admin/courses/$slug'
      path: '/$slug'
      fullPath: '/admin/courses/$slug'
      preLoaderRoute: typeof AdminCoursesSlugRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/_student/playground/$slug': {
      id: '/_student/playground/$slug'
      path: '/playground/$slug'
      fullPath: '/playground/$slug'
      preLoaderRoute: typeof StudentPlaygroundSlugRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/meetings/$sessionId': {
      id: '/_student/meetings/$sessionId'
      path: '/meetings/$sessionId'
      fullPath: '/meetings/$sessionId'
      preLoaderRoute: typeof StudentMeetingsSessionIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/learn/$slug': {
      id: '/_student/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof StudentLearnSlugRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentChallengesRoute: typeof StudentChallengesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLiveClassesRoute: typeof StudentLiveClassesRoute
  StudentMyBatchesRoute: typeof StudentMyBatchesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentLearnSlugRoute: typeof StudentLearnSlugRoute
  StudentMeetingsSessionIdRoute: typeof StudentMeetingsSessionIdRoute
  StudentPlaygroundSlugRoute: typeof StudentPlaygroundSlugRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentChallengesRoute: StudentChallengesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLiveClassesRoute: StudentLiveClassesRoute,
  StudentMyBatchesRoute: StudentMyBatchesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentLearnSlugRoute: StudentLearnSlugRoute,
  StudentMeetingsSessionIdRoute: StudentMeetingsSessionIdRoute,
  StudentPlaygroundSlugRoute: StudentPlaygroundSlugRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface AdminCoursesRouteChildren {
  AdminCoursesSlugRoute: typeof AdminCoursesSlugRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesSlugRoute: AdminCoursesSlugRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminRouteChildren {
  AdminBatchesRoute: typeof AdminBatchesRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminInstructorsRoute: typeof AdminInstructorsRoute
  AdminLiveClassesRoute: typeof AdminLiveClassesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBatchesRoute: AdminBatchesRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminInstructorsRoute: AdminInstructorsRoute,
  AdminLiveClassesRoute: AdminLiveClassesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRoute: StudentRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MentorshipRoute: MentorshipRoute,
  PracticeRoute: PracticeRoute,
  RegisterRoute: RegisterRoute,
  RoadmapsRoute: RoadmapsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
