/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated.challenges'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated.certificates'
import { Route as AuthenticatedPlaygroundSlugRouteImport } from './routes/_authenticated.playground.$slug'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated.learn.$slug'

const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaygroundSlugRoute =
  AuthenticatedPlaygroundSlugRouteImport.update({
    id: '/playground/$slug',
    path: '/playground/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/roadmaps': typeof RoadmapsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/playground/$slug': typeof AuthenticatedPlaygroundSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/roadmaps': typeof RoadmapsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/playground/$slug': typeof AuthenticatedPlaygroundSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/roadmaps': typeof RoadmapsRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/_authenticated/playground/$slug': typeof AuthenticatedPlaygroundSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/events'
    | '/login'
    | '/mentorship'
    | '/practice'
    | '/register'
    | '/roadmaps'
    | '/certificates'
    | '/challenges'
    | '/dashboard'
    | '/settings'
    | '/courses/$slug'
    | '/courses/'
    | '/learn/$slug'
    | '/playground/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/events'
    | '/login'
    | '/mentorship'
    | '/practice'
    | '/register'
    | '/roadmaps'
    | '/certificates'
    | '/challenges'
    | '/dashboard'
    | '/settings'
    | '/courses/$slug'
    | '/courses'
    | '/learn/$slug'
    | '/playground/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/community'
    | '/events'
    | '/login'
    | '/mentorship'
    | '/practice'
    | '/register'
    | '/roadmaps'
    | '/_authenticated/certificates'
    | '/_authenticated/challenges'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/courses/$slug'
    | '/courses/'
    | '/_authenticated/learn/$slug'
    | '/_authenticated/playground/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MentorshipRoute: typeof MentorshipRoute
  PracticeRoute: typeof PracticeRoute
  RegisterRoute: typeof RegisterRoute
  RoadmapsRoute: typeof RoadmapsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playground/$slug': {
      id: '/_authenticated/playground/$slug'
      path: '/playground/$slug'
      fullPath: '/playground/$slug'
      preLoaderRoute: typeof AuthenticatedPlaygroundSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/$slug': {
      id: '/_authenticated/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRoute
  AuthenticatedPlaygroundSlugRoute: typeof AuthenticatedPlaygroundSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRoute,
  AuthenticatedPlaygroundSlugRoute: AuthenticatedPlaygroundSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MentorshipRoute: MentorshipRoute,
  PracticeRoute: PracticeRoute,
  RegisterRoute: RegisterRoute,
  RoadmapsRoute: RoadmapsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
