/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as MeetingsMeetingIdRouteImport } from './routes/meetings.$meetingId'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as AuthStudentRouteImport } from './routes/_auth/student'
import { Route as AuthInstructorRouteImport } from './routes/_auth/instructor'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthStudentSettingsRouteImport } from './routes/_auth/student/settings'
import { Route as AuthStudentProfileRouteImport } from './routes/_auth/student/profile'
import { Route as AuthStudentLiveClassesRouteImport } from './routes/_auth/student/live-classes'
import { Route as AuthStudentDashboardRouteImport } from './routes/_auth/student/dashboard'
import { Route as AuthStudentCoursesRouteImport } from './routes/_auth/student/courses'
import { Route as AuthStudentChallengesRouteImport } from './routes/_auth/student/challenges'
import { Route as AuthStudentCertificatesRouteImport } from './routes/_auth/student/certificates'
import { Route as AuthStudentBatchesRouteImport } from './routes/_auth/student/batches'
import { Route as AuthInstructorMeetingsRouteImport } from './routes/_auth/instructor/meetings'
import { Route as AuthInstructorDashboardRouteImport } from './routes/_auth/instructor/dashboard'
import { Route as AuthInstructorCoursesRouteImport } from './routes/_auth/instructor/courses'
import { Route as AuthInstructorBatchesRouteImport } from './routes/_auth/instructor/batches'
import { Route as AuthAdminStudentsRouteImport } from './routes/_auth/admin/students'
import { Route as AuthAdminLoginRouteImport } from './routes/_auth/admin/login'
import { Route as AuthAdminLiveClassesRouteImport } from './routes/_auth/admin/live-classes'
import { Route as AuthAdminInstructorsRouteImport } from './routes/_auth/admin/instructors'
import { Route as AuthAdminInactiveUsersRouteImport } from './routes/_auth/admin/inactive-users'
import { Route as AuthAdminCoursesRouteImport } from './routes/_auth/admin/courses'
import { Route as AuthAdminBatchesRouteImport } from './routes/_auth/admin/batches'
import { Route as AuthInstructorCoursesIndexRouteImport } from './routes/_auth/instructor/courses/index'
import { Route as AuthAdminCoursesIndexRouteImport } from './routes/_auth/admin/courses/index'
import { Route as AuthStudentPlaygroundSlugRouteImport } from './routes/_auth/student/playground.$slug'
import { Route as AuthStudentLearnSlugRouteImport } from './routes/_auth/student/learn.$slug'
import { Route as AuthInstructorCoursesSlugRouteImport } from './routes/_auth/instructor/courses/$slug'
import { Route as AuthAdminCoursesSlugRouteImport } from './routes/_auth/admin/courses/$slug'

const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsMeetingIdRoute = MeetingsMeetingIdRouteImport.update({
  id: '/meetings/$meetingId',
  path: '/meetings/$meetingId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInstructorRoute = AuthInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthStudentSettingsRoute = AuthStudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentProfileRoute = AuthStudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentLiveClassesRoute = AuthStudentLiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentDashboardRoute = AuthStudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentCoursesRoute = AuthStudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentChallengesRoute = AuthStudentChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentCertificatesRoute = AuthStudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentBatchesRoute = AuthStudentBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthInstructorMeetingsRoute = AuthInstructorMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthInstructorRoute,
} as any)
const AuthInstructorDashboardRoute = AuthInstructorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthInstructorRoute,
} as any)
const AuthInstructorCoursesRoute = AuthInstructorCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthInstructorRoute,
} as any)
const AuthInstructorBatchesRoute = AuthInstructorBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthInstructorRoute,
} as any)
const AuthAdminStudentsRoute = AuthAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminLiveClassesRoute = AuthAdminLiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminInstructorsRoute = AuthAdminInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminInactiveUsersRoute = AuthAdminInactiveUsersRouteImport.update({
  id: '/inactive-users',
  path: '/inactive-users',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminCoursesRoute = AuthAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminBatchesRoute = AuthAdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthInstructorCoursesIndexRoute =
  AuthInstructorCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthInstructorCoursesRoute,
  } as any)
const AuthAdminCoursesIndexRoute = AuthAdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminCoursesRoute,
} as any)
const AuthStudentPlaygroundSlugRoute =
  AuthStudentPlaygroundSlugRouteImport.update({
    id: '/playground/$slug',
    path: '/playground/$slug',
    getParentRoute: () => AuthStudentRoute,
  } as any)
const AuthStudentLearnSlugRoute = AuthStudentLearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthInstructorCoursesSlugRoute =
  AuthInstructorCoursesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthInstructorCoursesRoute,
  } as any)
const AuthAdminCoursesSlugRoute = AuthAdminCoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthAdminCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/roadmaps': typeof RoadmapsRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/instructor': typeof AuthInstructorRouteWithChildren
  '/student': typeof AuthStudentRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/batches': typeof AuthAdminBatchesRoute
  '/admin/courses': typeof AuthAdminCoursesRouteWithChildren
  '/admin/inactive-users': typeof AuthAdminInactiveUsersRoute
  '/admin/instructors': typeof AuthAdminInstructorsRoute
  '/admin/live-classes': typeof AuthAdminLiveClassesRoute
  '/admin/login': typeof AuthAdminLoginRoute
  '/admin/students': typeof AuthAdminStudentsRoute
  '/instructor/batches': typeof AuthInstructorBatchesRoute
  '/instructor/courses': typeof AuthInstructorCoursesRouteWithChildren
  '/instructor/dashboard': typeof AuthInstructorDashboardRoute
  '/instructor/meetings': typeof AuthInstructorMeetingsRoute
  '/student/batches': typeof AuthStudentBatchesRoute
  '/student/certificates': typeof AuthStudentCertificatesRoute
  '/student/challenges': typeof AuthStudentChallengesRoute
  '/student/courses': typeof AuthStudentCoursesRoute
  '/student/dashboard': typeof AuthStudentDashboardRoute
  '/student/live-classes': typeof AuthStudentLiveClassesRoute
  '/student/profile': typeof AuthStudentProfileRoute
  '/student/settings': typeof AuthStudentSettingsRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/admin/courses/$slug': typeof AuthAdminCoursesSlugRoute
  '/instructor/courses/$slug': typeof AuthInstructorCoursesSlugRoute
  '/student/learn/$slug': typeof AuthStudentLearnSlugRoute
  '/student/playground/$slug': typeof AuthStudentPlaygroundSlugRoute
  '/admin/courses/': typeof AuthAdminCoursesIndexRoute
  '/instructor/courses/': typeof AuthInstructorCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/roadmaps': typeof RoadmapsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/instructor': typeof AuthInstructorRouteWithChildren
  '/student': typeof AuthStudentRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/batches': typeof AuthAdminBatchesRoute
  '/admin/inactive-users': typeof AuthAdminInactiveUsersRoute
  '/admin/instructors': typeof AuthAdminInstructorsRoute
  '/admin/live-classes': typeof AuthAdminLiveClassesRoute
  '/admin/login': typeof AuthAdminLoginRoute
  '/admin/students': typeof AuthAdminStudentsRoute
  '/instructor/batches': typeof AuthInstructorBatchesRoute
  '/instructor/dashboard': typeof AuthInstructorDashboardRoute
  '/instructor/meetings': typeof AuthInstructorMeetingsRoute
  '/student/batches': typeof AuthStudentBatchesRoute
  '/student/certificates': typeof AuthStudentCertificatesRoute
  '/student/challenges': typeof AuthStudentChallengesRoute
  '/student/courses': typeof AuthStudentCoursesRoute
  '/student/dashboard': typeof AuthStudentDashboardRoute
  '/student/live-classes': typeof AuthStudentLiveClassesRoute
  '/student/profile': typeof AuthStudentProfileRoute
  '/student/settings': typeof AuthStudentSettingsRoute
  '/admin': typeof AuthAdminIndexRoute
  '/admin/courses/$slug': typeof AuthAdminCoursesSlugRoute
  '/instructor/courses/$slug': typeof AuthInstructorCoursesSlugRoute
  '/student/learn/$slug': typeof AuthStudentLearnSlugRoute
  '/student/playground/$slug': typeof AuthStudentPlaygroundSlugRoute
  '/admin/courses': typeof AuthAdminCoursesIndexRoute
  '/instructor/courses': typeof AuthInstructorCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/mentorship': typeof MentorshipRoute
  '/practice': typeof PracticeRoute
  '/register': typeof RegisterRoute
  '/roadmaps': typeof RoadmapsRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/instructor': typeof AuthInstructorRouteWithChildren
  '/_auth/student': typeof AuthStudentRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/_auth/admin/batches': typeof AuthAdminBatchesRoute
  '/_auth/admin/courses': typeof AuthAdminCoursesRouteWithChildren
  '/_auth/admin/inactive-users': typeof AuthAdminInactiveUsersRoute
  '/_auth/admin/instructors': typeof AuthAdminInstructorsRoute
  '/_auth/admin/live-classes': typeof AuthAdminLiveClassesRoute
  '/_auth/admin/login': typeof AuthAdminLoginRoute
  '/_auth/admin/students': typeof AuthAdminStudentsRoute
  '/_auth/instructor/batches': typeof AuthInstructorBatchesRoute
  '/_auth/instructor/courses': typeof AuthInstructorCoursesRouteWithChildren
  '/_auth/instructor/dashboard': typeof AuthInstructorDashboardRoute
  '/_auth/instructor/meetings': typeof AuthInstructorMeetingsRoute
  '/_auth/student/batches': typeof AuthStudentBatchesRoute
  '/_auth/student/certificates': typeof AuthStudentCertificatesRoute
  '/_auth/student/challenges': typeof AuthStudentChallengesRoute
  '/_auth/student/courses': typeof AuthStudentCoursesRoute
  '/_auth/student/dashboard': typeof AuthStudentDashboardRoute
  '/_auth/student/live-classes': typeof AuthStudentLiveClassesRoute
  '/_auth/student/profile': typeof AuthStudentProfileRoute
  '/_auth/student/settings': typeof AuthStudentSettingsRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/admin/courses/$slug': typeof AuthAdminCoursesSlugRoute
  '/_auth/instructor/courses/$slug': typeof AuthInstructorCoursesSlugRoute
  '/_auth/student/learn/$slug': typeof AuthStudentLearnSlugRoute
  '/_auth/student/playground/$slug': typeof AuthStudentPlaygroundSlugRoute
  '/_auth/admin/courses/': typeof AuthAdminCoursesIndexRoute
  '/_auth/instructor/courses/': typeof AuthInstructorCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/events'
    | '/login'
    | '/mentorship'
    | '/practice'
    | '/register'
    | '/roadmaps'
    | '/admin'
    | '/dashboard'
    | '/instructor'
    | '/student'
    | '/courses/$slug'
    | '/meetings/$meetingId'
    | '/courses/'
    | '/admin/batches'
    | '/admin/courses'
    | '/admin/inactive-users'
    | '/admin/instructors'
    | '/admin/live-classes'
    | '/admin/login'
    | '/admin/students'
    | '/instructor/batches'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/instructor/meetings'
    | '/student/batches'
    | '/student/certificates'
    | '/student/challenges'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/live-classes'
    | '/student/profile'
    | '/student/settings'
    | '/admin/'
    | '/admin/courses/$slug'
    | '/instructor/courses/$slug'
    | '/student/learn/$slug'
    | '/student/playground/$slug'
    | '/admin/courses/'
    | '/instructor/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/events'
    | '/login'
    | '/mentorship'
    | '/practice'
    | '/register'
    | '/roadmaps'
    | '/dashboard'
    | '/instructor'
    | '/student'
    | '/courses/$slug'
    | '/meetings/$meetingId'
    | '/courses'
    | '/admin/batches'
    | '/admin/inactive-users'
    | '/admin/instructors'
    | '/admin/live-classes'
    | '/admin/login'
    | '/admin/students'
    | '/instructor/batches'
    | '/instructor/dashboard'
    | '/instructor/meetings'
    | '/student/batches'
    | '/student/certificates'
    | '/student/challenges'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/live-classes'
    | '/student/profile'
    | '/student/settings'
    | '/admin'
    | '/admin/courses/$slug'
    | '/instructor/courses/$slug'
    | '/student/learn/$slug'
    | '/student/playground/$slug'
    | '/admin/courses'
    | '/instructor/courses'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/community'
    | '/events'
    | '/login'
    | '/mentorship'
    | '/practice'
    | '/register'
    | '/roadmaps'
    | '/_auth/admin'
    | '/_auth/dashboard'
    | '/_auth/instructor'
    | '/_auth/student'
    | '/courses/$slug'
    | '/meetings/$meetingId'
    | '/courses/'
    | '/_auth/admin/batches'
    | '/_auth/admin/courses'
    | '/_auth/admin/inactive-users'
    | '/_auth/admin/instructors'
    | '/_auth/admin/live-classes'
    | '/_auth/admin/login'
    | '/_auth/admin/students'
    | '/_auth/instructor/batches'
    | '/_auth/instructor/courses'
    | '/_auth/instructor/dashboard'
    | '/_auth/instructor/meetings'
    | '/_auth/student/batches'
    | '/_auth/student/certificates'
    | '/_auth/student/challenges'
    | '/_auth/student/courses'
    | '/_auth/student/dashboard'
    | '/_auth/student/live-classes'
    | '/_auth/student/profile'
    | '/_auth/student/settings'
    | '/_auth/admin/'
    | '/_auth/admin/courses/$slug'
    | '/_auth/instructor/courses/$slug'
    | '/_auth/student/learn/$slug'
    | '/_auth/student/playground/$slug'
    | '/_auth/admin/courses/'
    | '/_auth/instructor/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MentorshipRoute: typeof MentorshipRoute
  PracticeRoute: typeof PracticeRoute
  RegisterRoute: typeof RegisterRoute
  RoadmapsRoute: typeof RoadmapsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  MeetingsMeetingIdRoute: typeof MeetingsMeetingIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$meetingId': {
      id: '/meetings/$meetingId'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof MeetingsMeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/student': {
      id: '/_auth/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/instructor': {
      id: '/_auth/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AuthInstructorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/student/settings': {
      id: '/_auth/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof AuthStudentSettingsRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/profile': {
      id: '/_auth/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthStudentProfileRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/live-classes': {
      id: '/_auth/student/live-classes'
      path: '/live-classes'
      fullPath: '/student/live-classes'
      preLoaderRoute: typeof AuthStudentLiveClassesRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/dashboard': {
      id: '/_auth/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthStudentDashboardRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/courses': {
      id: '/_auth/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof AuthStudentCoursesRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/challenges': {
      id: '/_auth/student/challenges'
      path: '/challenges'
      fullPath: '/student/challenges'
      preLoaderRoute: typeof AuthStudentChallengesRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/certificates': {
      id: '/_auth/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof AuthStudentCertificatesRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/batches': {
      id: '/_auth/student/batches'
      path: '/batches'
      fullPath: '/student/batches'
      preLoaderRoute: typeof AuthStudentBatchesRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/instructor/meetings': {
      id: '/_auth/instructor/meetings'
      path: '/meetings'
      fullPath: '/instructor/meetings'
      preLoaderRoute: typeof AuthInstructorMeetingsRouteImport
      parentRoute: typeof AuthInstructorRoute
    }
    '/_auth/instructor/dashboard': {
      id: '/_auth/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof AuthInstructorDashboardRouteImport
      parentRoute: typeof AuthInstructorRoute
    }
    '/_auth/instructor/courses': {
      id: '/_auth/instructor/courses'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof AuthInstructorCoursesRouteImport
      parentRoute: typeof AuthInstructorRoute
    }
    '/_auth/instructor/batches': {
      id: '/_auth/instructor/batches'
      path: '/batches'
      fullPath: '/instructor/batches'
      preLoaderRoute: typeof AuthInstructorBatchesRouteImport
      parentRoute: typeof AuthInstructorRoute
    }
    '/_auth/admin/students': {
      id: '/_auth/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthAdminStudentsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/login': {
      id: '/_auth/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/live-classes': {
      id: '/_auth/admin/live-classes'
      path: '/live-classes'
      fullPath: '/admin/live-classes'
      preLoaderRoute: typeof AuthAdminLiveClassesRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/instructors': {
      id: '/_auth/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AuthAdminInstructorsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/inactive-users': {
      id: '/_auth/admin/inactive-users'
      path: '/inactive-users'
      fullPath: '/admin/inactive-users'
      preLoaderRoute: typeof AuthAdminInactiveUsersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/courses': {
      id: '/_auth/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthAdminCoursesRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/batches': {
      id: '/_auth/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AuthAdminBatchesRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/instructor/courses/': {
      id: '/_auth/instructor/courses/'
      path: '/'
      fullPath: '/instructor/courses/'
      preLoaderRoute: typeof AuthInstructorCoursesIndexRouteImport
      parentRoute: typeof AuthInstructorCoursesRoute
    }
    '/_auth/admin/courses/': {
      id: '/_auth/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthAdminCoursesIndexRouteImport
      parentRoute: typeof AuthAdminCoursesRoute
    }
    '/_auth/student/playground/$slug': {
      id: '/_auth/student/playground/$slug'
      path: '/playground/$slug'
      fullPath: '/student/playground/$slug'
      preLoaderRoute: typeof AuthStudentPlaygroundSlugRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/learn/$slug': {
      id: '/_auth/student/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/student/learn/$slug'
      preLoaderRoute: typeof AuthStudentLearnSlugRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/instructor/courses/$slug': {
      id: '/_auth/instructor/courses/$slug'
      path: '/$slug'
      fullPath: '/instructor/courses/$slug'
      preLoaderRoute: typeof AuthInstructorCoursesSlugRouteImport
      parentRoute: typeof AuthInstructorCoursesRoute
    }
    '/_auth/admin/courses/$slug': {
      id: '/_auth/admin/courses/$slug'
      path: '/$slug'
      fullPath: '/admin/courses/$slug'
      preLoaderRoute: typeof AuthAdminCoursesSlugRouteImport
      parentRoute: typeof AuthAdminCoursesRoute
    }
  }
}

interface AuthAdminCoursesRouteChildren {
  AuthAdminCoursesSlugRoute: typeof AuthAdminCoursesSlugRoute
  AuthAdminCoursesIndexRoute: typeof AuthAdminCoursesIndexRoute
}

const AuthAdminCoursesRouteChildren: AuthAdminCoursesRouteChildren = {
  AuthAdminCoursesSlugRoute: AuthAdminCoursesSlugRoute,
  AuthAdminCoursesIndexRoute: AuthAdminCoursesIndexRoute,
}

const AuthAdminCoursesRouteWithChildren =
  AuthAdminCoursesRoute._addFileChildren(AuthAdminCoursesRouteChildren)

interface AuthAdminRouteChildren {
  AuthAdminBatchesRoute: typeof AuthAdminBatchesRoute
  AuthAdminCoursesRoute: typeof AuthAdminCoursesRouteWithChildren
  AuthAdminInactiveUsersRoute: typeof AuthAdminInactiveUsersRoute
  AuthAdminInstructorsRoute: typeof AuthAdminInstructorsRoute
  AuthAdminLiveClassesRoute: typeof AuthAdminLiveClassesRoute
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
  AuthAdminStudentsRoute: typeof AuthAdminStudentsRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminBatchesRoute: AuthAdminBatchesRoute,
  AuthAdminCoursesRoute: AuthAdminCoursesRouteWithChildren,
  AuthAdminInactiveUsersRoute: AuthAdminInactiveUsersRoute,
  AuthAdminInstructorsRoute: AuthAdminInstructorsRoute,
  AuthAdminLiveClassesRoute: AuthAdminLiveClassesRoute,
  AuthAdminLoginRoute: AuthAdminLoginRoute,
  AuthAdminStudentsRoute: AuthAdminStudentsRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthInstructorCoursesRouteChildren {
  AuthInstructorCoursesSlugRoute: typeof AuthInstructorCoursesSlugRoute
  AuthInstructorCoursesIndexRoute: typeof AuthInstructorCoursesIndexRoute
}

const AuthInstructorCoursesRouteChildren: AuthInstructorCoursesRouteChildren = {
  AuthInstructorCoursesSlugRoute: AuthInstructorCoursesSlugRoute,
  AuthInstructorCoursesIndexRoute: AuthInstructorCoursesIndexRoute,
}

const AuthInstructorCoursesRouteWithChildren =
  AuthInstructorCoursesRoute._addFileChildren(
    AuthInstructorCoursesRouteChildren,
  )

interface AuthInstructorRouteChildren {
  AuthInstructorBatchesRoute: typeof AuthInstructorBatchesRoute
  AuthInstructorCoursesRoute: typeof AuthInstructorCoursesRouteWithChildren
  AuthInstructorDashboardRoute: typeof AuthInstructorDashboardRoute
  AuthInstructorMeetingsRoute: typeof AuthInstructorMeetingsRoute
}

const AuthInstructorRouteChildren: AuthInstructorRouteChildren = {
  AuthInstructorBatchesRoute: AuthInstructorBatchesRoute,
  AuthInstructorCoursesRoute: AuthInstructorCoursesRouteWithChildren,
  AuthInstructorDashboardRoute: AuthInstructorDashboardRoute,
  AuthInstructorMeetingsRoute: AuthInstructorMeetingsRoute,
}

const AuthInstructorRouteWithChildren = AuthInstructorRoute._addFileChildren(
  AuthInstructorRouteChildren,
)

interface AuthStudentRouteChildren {
  AuthStudentBatchesRoute: typeof AuthStudentBatchesRoute
  AuthStudentCertificatesRoute: typeof AuthStudentCertificatesRoute
  AuthStudentChallengesRoute: typeof AuthStudentChallengesRoute
  AuthStudentCoursesRoute: typeof AuthStudentCoursesRoute
  AuthStudentDashboardRoute: typeof AuthStudentDashboardRoute
  AuthStudentLiveClassesRoute: typeof AuthStudentLiveClassesRoute
  AuthStudentProfileRoute: typeof AuthStudentProfileRoute
  AuthStudentSettingsRoute: typeof AuthStudentSettingsRoute
  AuthStudentLearnSlugRoute: typeof AuthStudentLearnSlugRoute
  AuthStudentPlaygroundSlugRoute: typeof AuthStudentPlaygroundSlugRoute
}

const AuthStudentRouteChildren: AuthStudentRouteChildren = {
  AuthStudentBatchesRoute: AuthStudentBatchesRoute,
  AuthStudentCertificatesRoute: AuthStudentCertificatesRoute,
  AuthStudentChallengesRoute: AuthStudentChallengesRoute,
  AuthStudentCoursesRoute: AuthStudentCoursesRoute,
  AuthStudentDashboardRoute: AuthStudentDashboardRoute,
  AuthStudentLiveClassesRoute: AuthStudentLiveClassesRoute,
  AuthStudentProfileRoute: AuthStudentProfileRoute,
  AuthStudentSettingsRoute: AuthStudentSettingsRoute,
  AuthStudentLearnSlugRoute: AuthStudentLearnSlugRoute,
  AuthStudentPlaygroundSlugRoute: AuthStudentPlaygroundSlugRoute,
}

const AuthStudentRouteWithChildren = AuthStudentRoute._addFileChildren(
  AuthStudentRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthInstructorRoute: typeof AuthInstructorRouteWithChildren
  AuthStudentRoute: typeof AuthStudentRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthInstructorRoute: AuthInstructorRouteWithChildren,
  AuthStudentRoute: AuthStudentRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MentorshipRoute: MentorshipRoute,
  PracticeRoute: PracticeRoute,
  RegisterRoute: RegisterRoute,
  RoadmapsRoute: RoadmapsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  MeetingsMeetingIdRoute: MeetingsMeetingIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
